ajax/urls.py
from django.conf.urls import patterns, url
from reservar import views
urlpatterns = patterns('',
    url(r'^paquete/precio/$','reservar.views.cancelado', name='cancelado'),
)

ppll/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from pyllik import views
from django.conf import settings

handler404 = 'pyllik.views.error404'
handler403 = 'pyllik.views.error403'
handler500 = 'pyllik.views.error500'

urlpatterns = patterns('',
    url(r'^$',views.index,name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('usuario.urls')),
    url(r'^crm/', include('pyllik.urls')),
    url(r'^logos/', include('pyllik.urls')),
    url(r'^reservar/', include('reservar.urls')),
    url(r'^pdf/', include('page.urls')),
    url(r'^ajax/', include('ajax.urls')),
    url(r'^carga/(?P<path>.*)$', 'django.views.static.serve',
       {'document_root': settings.MEDIA_ROOT, } ),
)

pyllik/urls.py
from django.conf.urls import patterns, include, url
urlpatterns = patterns('',
    # Paquetes
    url(r'^paquetes$','pyllik.views.paqueteList', name='paqueteList'),
    url(r'^paquetes/rendimiento$','pyllik.views.paquetesRendimiento', name='paquetesRendimiento'),
    url(r'^paquete/detail/(?P<id>\d+)$','pyllik.views.paqueteDetail', name='paqueteDetail'),
    url(r'^paquete/edit/(?P<id>\d+)$','pyllik.views.paqueteEdit', name='paqueteEdit'),
    url(r'^paquete/add/$','pyllik.views.paqueteAdd', name='paqueteAdd'),
    # Empresa
    url(r'^$','pyllik.views.index', name='index'),
    url(r'^information/$','pyllik.views.empresaDetail', name='empresaDetail'),
    url(r'^edit/$','pyllik.views.empresaEdit', name='empresaEdit'),
    url(r'^edit/paypal_account$','pyllik.views.paypal_account', name='paypal_account'),
    url(r'^edit/logo$','pyllik.views.logo', name='logo'),
    # Reservas
    url(r'^reservas$','pyllik.views.reservaList', name='reservaList'),
    url(r'^reservas/confirmadas$','pyllik.views.reservaConfirmadas', name='reservaConfirmadas'),
    #url(r'^reservas/analytics$','pyllik.views.reservaAnalytics', name='reservaAnalytics'),
    url(r'^reserva/detail/(?P<id>\d+)$','pyllik.views.reservaDetail', name='reservaDetail'),
    url(r'^reserva/(?P<id>\d+)/add/pasajeros$','pyllik.views.reservaAddPasajero', name='reservaAddPasajero'),
    url(r'^reserva/edit/estado/(?P<id>\d+)$','pyllik.views.reservaEstado', name='reservaEstado'),
    #rl(r'^reserva/edit/(?P<id>\d+)$','pyllik.views.reservaEdit', name='reservaEdit'),
    url(r'^reserva/paquete/(?P<sku>\w{7})$','pyllik.views.reservaPaquete', name='reservaPaquete'),
    url(r'^pagos$','pyllik.views.pagos', name='pagos'),
    # Pasajeros
    url(r'^pasajeros$','pyllik.views.pasajeros', name='pasajeros'),
    url(r'^pasajero/add$','pyllik.views.pasajeroAdd', name='pasajeroAdd'),
    url(r'^pasajero/detail/(?P<id>\d+)$','pyllik.views.pasajeroDetail', name='pasajeroDetail'),
    url(r'^pasajero/edit/(?P<id>\d+)$','pyllik.views.pasajeroEdit', name='pasajeroEdit'),
    # Clientes
    url(r'^clientes$','pyllik.views.clientes', name='clientes'),
    url(r'^cliente/add/$','pyllik.views.clienteAdd', name='clienteAdd'),
    url(r'^cliente/detail/(?P<id>\d+)$','pyllik.views.clienteDetail', name='clienteDetail'),
    url(r'^cliente/edit/(?P<id>\d+)$','pyllik.views.clienteEdit', name='clienteEdit'),
    # Clientes
    url(r'^trabajadores$','pyllik.views.trabajadores', name='trabajadores'),
    url(r'^trabajador/add/$','pyllik.views.trabajadorAdd', name='trabajadorAdd'),
    url(r'^trabajador/detail/(?P<id>\d+)$','pyllik.views.trabajadorDetail', name='trabajadorDetail'),
    url(r'^trabajador/edit/(?P<id>\d+)$','pyllik.views.trabajadorEdit', name='trabajadorEdit'),
)

pyllik/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from thumbs import ImageWithThumbsField
import uuid,random
def Abreviatura(razon_social):
    abreviatura = razon_social[:3]
    abreviatura += random.choice("abcdefghijklm")
    return abreviatura.upper()
class Pais(models.Model):
    nombre = models.CharField(max_length=30)
    def __unicode__(self):
        return self.nombre
class Rubro(models.Model):
    nombre = models.CharField(max_length=120)
    def __unicode__(self):
        return self.nombre
class Empresa(models.Model):
    rubro = models.ForeignKey(Rubro,default=1)
    razon_social = models.CharField(max_length=100)
    ruc = models.CharField(max_length=11)
    direccion = models.CharField(max_length=120)
    telefono = models.CharField(max_length=120, blank=True)
    claro = models.CharField(max_length=20, blank=True)
    movistar = models.CharField(max_length=20, blank=True)
    email = models.EmailField(max_length=64, blank=True)
    web = models.URLField(max_length=64, blank=True)
    logo = ImageWithThumbsField(upload_to='logos_empresa', sizes=((150,50),))
    terminos_condiciones = models.URLField(max_length=120, blank=True, help_text="URL Terminos y condiciones.")
    abreviatura = models.CharField(max_length=4,unique=True,editable=False)
    paypal_email = models.EmailField(max_length=100,help_text="E-mail relacionado con paypal")
    paypal_at = models.CharField(max_length=64,help_text="Código de identicacion en paypal") # IdentityToken
    code = models.CharField(max_length=32,default=uuid.uuid1().hex,editable=False)
    creado = models.DateField(auto_now_add=True, editable=False)
    editado = models.DateTimeField(auto_now=True, editable=False)
    def save(self, *args, **kwargs):
        if len(self.abreviatura) < 2:
            self.abreviatura = Abreviatura(self.razon_social)
        super(Empresa,self).save(*args,**kwargs)
    def __unicode__(self):
        return self.razon_social
class TipoDocumento(models.Model):
    nombre = models.CharField(max_length=30)
    def __unicode__(self):
        return self.nombre
class Trabajador(models.Model):
    user = models.OneToOneField(User,primary_key=True)
    doc_nro = models.CharField(max_length=10,verbose_name="D. I.")
    direccion = models.CharField(max_length=60)
    telefono = models.CharField(max_length=60)
    celular = models.CharField(max_length=60)
    observaciones = models.TextField(blank=True)
    empresa = models.ForeignKey(Empresa)
    foto = ImageWithThumbsField(upload_to='trabajadores', sizes=((210,320),))
    def __unicode__(self):
        return str(self.user)
class TrabajadorContacto(models.Model):
    nombre = models.CharField(max_length=30)
    apellidos = models.CharField(max_length=50)
    direccion = models.CharField(max_length=100)
    telefono = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    trabajador = models.ForeignKey(Trabajador)
    empresa = models.ForeignKey(Empresa)
    def __unicode__(self):
        return self.nombre
class TipoPasajero(models.Model):
    nombre = models.CharField(max_length=30)
    def __unicode__(self):
        return self.nombre
class Pasajero(models.Model):
    nombre = models.CharField(max_length=30)
    apellidos = models.CharField(max_length=60)
    doc_tipo = models.ForeignKey(TipoDocumento)
    doc_nro = models.CharField(max_length=10)
    email = models.EmailField(max_length=60,blank=True)
    telefono = models.CharField(max_length=50, blank=True)
    pais = models.ForeignKey(Pais,null=True, blank=True)
    tipo = models.ForeignKey(TipoPasajero,default=4,blank=True)
    observacion = models.TextField(blank=True)
    empresa = models.ForeignKey(Empresa,null=True, blank=True,editable=False)
    creado = models.DateField(auto_now_add=True, editable=False)
    editado = models.DateTimeField(auto_now=True, editable=False)
    def __unicode__(self):
        return self.nombre
BOOL_CHOICES = ((True, 'Habitilido'), (False, 'Deshabilitado'))
def sku(last_sku):
    sku = last_sku[:4]
    sku += str(int(last_sku[4:]) + 1).zfill(3)
    return sku;
class Paquete(models.Model):
    sku = models.CharField(max_length=7,unique=True,editable=False)
    nombre = models.CharField(max_length=60,help_text="Coloque el nombre del paquete, tal como aparece en su sitio web.")
    precio = models.FloatField(default=0, validators=[MinValueValidator(0)],help_text="Coloque el precio del paquete, tal como aparece en su sitio web. Los precios son en Dólares Americanos (USD $)")
    porcentaje = models.FloatField(default=100, validators=[MinValueValidator(0),MaxValueValidator(100)],help_text="Coloque el porcentaje del Pre pago que el sistema va a cobrar por pasajero, el monto en USD $ se actualiza automáticamente.")
    pre_pago = models.FloatField(default=0, validators=[MinValueValidator(0)],help_text="Coloque el monto en USD $ del Pre pago que el sistema va a cobrar por pasajero, el monto en % se acutaliza automáticamente")
    descripcion = models.TextField(max_length=500, blank=True, help_text="Este es una pequeña descripción del paquete que está Ud. vendiendo. Debe concordar con lo que aparece en su página web.")
    empresa = models.ForeignKey(Empresa,editable=False)
    link = models.URLField(max_length=120, blank=True, help_text="Coloque el link del Paquete que aparece en su página web. Verifique que sea el link correcto.")
    estado = models.BooleanField(default=True,choices=BOOL_CHOICES, help_text="Active el Estado si desea que este paquete este activo, si quita el check el paquete se desactivará y no podrá userse.")
    creado = models.DateField(auto_now_add=True, editable=False)
    editado = models.DateTimeField(auto_now=True, editable=False)
    def save(self, *args, **kwargs):
        if len(self.sku) < 7:
            empresa_id = self.empresa.id
            ultimo = Paquete.objects.filter(empresa_id = empresa_id).latest('id')
            self.sku = sku(ultimo.sku)
        super(Paquete,self).save(*args,**kwargs)
    def __unicode__(self):
        return self.nombre
class TipoCliente(models.Model):
    nombre = models.CharField(max_length=30)
    def __unicode__(self):
        return self.nombre
class Cliente(models.Model):
    nombre = models.CharField(max_length=30,blank=True)
    apellidos = models.CharField(max_length=60,blank=True)
    doc_tipo = models.ForeignKey(TipoDocumento,null=True,blank=True)
    doc_nro = models.CharField(max_length=10,blank=True)
    email = models.EmailField(max_length=60)
    telefono = models.CharField(max_length=50, blank=True)
    celular = models.CharField(max_length=50, blank=True)
    pais = models.ForeignKey(Pais,null=True, blank=True)
    tipo = models.ForeignKey(TipoCliente, default=1)
    observacion = models.TextField(blank=True)
    empresa = models.ForeignKey(Empresa,editable=False)
    creado = models.DateField(auto_now_add=True, editable=False)
    editado = models.DateTimeField(auto_now=True, editable=False)
    def __unicode__(self):
        return self.email
class FormaPago(models.Model):
    nombre = models.CharField(max_length=30)
    def __unicode__(self):
        return self.nombre
class EstadoPago(models.Model):
    nombre = models.CharField(max_length=30)
    def __unicode__(self):
        return self.nombre
class EstadoReserva(models.Model):
    nombre = models.CharField(max_length=30)
    def __unicode__(self):
        return self.nombre
class ReservadoMediante(models.Model):
    nombre = models.CharField(max_length=30)
    def __unicode__(self):
        return self.nombre
class Reserva(models.Model):
    paquete = models.ForeignKey(Paquete)
    precio = models.FloatField(blank=True)
    pre_pago = models.FloatField(blank=True)
    # Porcentaje
    fecha_viaje = models.DateField()
    cantidad_pasajeros = models.IntegerField()
    pasajeros = models.ManyToManyField(Pasajero, blank=True)
    ip = models.GenericIPAddressField(null=True,blank=True)
    reservado_mediante = models.ForeignKey(ReservadoMediante,default=1)
    cliente = models.ForeignKey(Cliente)
    estado = models.ForeignKey(EstadoReserva,verbose_name="Estado Reserva")
    estado_pago = models.ForeignKey(EstadoPago)
    code = models.CharField(max_length=32,default=uuid.uuid1().hex,editable=False)
    nuevo = models.BooleanField(default=True)
    creado = models.DateTimeField(auto_now_add=True, editable=False)
    editado = models.DateTimeField(auto_now=True, editable=False)
    empresa = models.ForeignKey(Empresa)
    def save(self, *args, **kwargs):
    # Esto esta mal
        self.empresa = self.paquete.empresa
        self.pre_pago = self.paquete.pre_pago
        self.precio = self.paquete.precio
        super(Reserva,self).save(*args,**kwargs)
    def __unicode__(self):
        return "Una reserva de "+str(self.id)
    def precioTotal(self):
        return int(self.cantidad_pasajeros) * self.precio
    def precioTotalPrePago(self):
        return int(self.cantidad_pasajeros) * self.pre_pago
class ComentarioReserva(models.Model):
    comentario = models.TextField()
    empresa = models.ForeignKey(Empresa)
    reserva = models.ForeignKey(Reserva)
    creado = models.DateTimeField(auto_now_add=True, editable=False)
    estado = models.BooleanField(default=True)
    def __unicode__(self):
        return "Comentario"
PAGO_CHOICES = ((True, 'ACEPTADO'), (False, 'DEVUELTO'))
class Pago(models.Model):
    reserva = models.ForeignKey(Reserva)
    precio = models.FloatField(default=0,verbose_name="Monto pagado")
    creado = models.DateTimeField(null=True,verbose_name="Fecha de pago")
    forma_pago = models.ForeignKey(FormaPago)
    estado = models.BooleanField(default=True,choices=PAGO_CHOICES)
    ip = models.GenericIPAddressField(null=True,blank=True)
    tx = models.CharField(max_length=64, blank=True)
    verificado = models.BooleanField(default=False)
    empresa = models.ForeignKey(Empresa)

pyllik/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Paquete, Empresa, Pasajero, Cliente,Reserva,Trabajador
from django.contrib.auth.models import User
from suit_ckeditor.widgets import CKEditorWidget

class PaqueteForm(forms.ModelForm):
    precio = forms.FloatField(required=True,min_value=0,help_text="Coloque el precio del paquete, tal como aparece en su sitio web. Los precios son en Dólares Americanos (USD $)")
    class Meta:
        model = Paquete
        fields = ('nombre', 'precio','porcentaje','pre_pago','descripcion','link','estado')
        widgets = {
            'descripcion': CKEditorWidget(editor_options={'startupFocus': True})
        }
class PaqueteEditForm(forms.ModelForm):
    precio = forms.FloatField(required=True,min_value=0,help_text="Coloque el precio del paquete, tal como aparece en su sitio web. Los precios son en Dólares Americanos (USD $)")
    class Meta:
        model = Paquete
        fields = ('nombre', 'precio','porcentaje','pre_pago','descripcion','link','estado')
        widgets = {
            'descripcion': CKEditorWidget(editor_options={'startupFocus': True})
        }
class EmpresaForm(forms.ModelForm):
    razon_social = forms.CharField(min_length=3,max_length=40)
    direccion = forms.CharField(max_length=40)
    telefono = forms.CharField(max_length=30)
    ruc = forms.CharField(min_length=11)
    abreviatura = forms.CharField(min_length=3)
    class Meta:
        model = Empresa
        fields  = ('rubro','ruc','razon_social','direccion','abreviatura','telefono',)
class EmpresaFormEdit(forms.ModelForm):
    razon_social = forms.CharField(max_length=40)
    direccion = forms.CharField(max_length=40)
    telefono = forms.CharField(max_length=30)
    ruc = forms.CharField(min_length=11)
    class Meta:
        model = Empresa
        exclude = ('trabajadores','logo','nro_paquetes','paypal_email','paypal_at','abreviatura')
class EmpresaFormEditLogo(forms.ModelForm):
    class Meta:
        model = Empresa
        fields  = ('logo',)
class PaypalAccountForm(forms.ModelForm):
    paypal_email = forms.CharField(required=True,max_length=60)
    paypal_at = forms.CharField(required=True,max_length=64)
    class Meta:
        model = Empresa
        fields  = ('paypal_email','paypal_at',)
class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ('nombre','apellidos', 'doc_tipo','doc_nro','email','telefono','celular','pais')
class TrabajadorForm(forms.ModelForm):
    class Meta:
        model = Trabajador
        fields = ('doc_nro','direccion','doc_nro','telefono','celular')
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','email','username','password',)
        widgets = {
            'password':forms.PasswordInput(),
        }
class PasajeroForm(forms.ModelForm):
    class Meta:
        model = Pasajero
        exclude = ('editado','creado')
class ReservaEstadoForm(forms.ModelForm):
    class Meta:
        model = Reserva
        fields  = ('estado','estado_pago',)
class ReservaForm(forms.ModelForm):
    class Meta:
        model = Reserva
        fields=('fecha_viaje','cantidad_pasajeros','estado_pago','reservado_mediante','estado',)
# Buscar
class BuscarReservaForm(forms.ModelForm):
    def __init__(self, empresa_id=1, *args, **kwargs):
        super(BuscarReservaForm, self).__init__(*args, **kwargs)
        self.fields['paquete'].queryset = Paquete.objects.filter(empresa_id=empresa_id)
    class Meta:
        model = Reserva
        fields = ('fecha_viaje','estado','estado_pago','paquete',)
class BuscarClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ('email','pais',)
class BuscarPasajeroForm(forms.ModelForm):
    class Meta:
        model = Pasajero
        fields = ('doc_nro','pais',)

pyllik/templates/paquete/add.html
{% extends "layout/base_admin.html" %}
{% block title %}Agregar Paquete <small>new</small>   {% endblock %}
{% block options %}
    <li class="active"><a href="#">Nuevo</a></li>
    <li><a href="../../paquetes">Listar</a></li>
{% endblock %}
{% block content %}
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js"></script>
<script type="text/javascript">
    $(function(){
        $("#id_link").change(function() {
            valor = $("#id_link").val();
            var valido=valor.substring(0,4);
            if(valido!="http"){
                var hh = "http://";
                $("#id_link").val(hh+valor);
            }
        });

        $("#id_precio, #id_porcentaje").change(function() {
            pre = $("#id_precio").val();
            por = $("#id_porcentaje").val();
            $("#id_pre_pago").val(pre*por/100);
        });

        $('#id_nombre, #id_precio, #id_porcentaje, #id_pre_pago, #id_descripcion, #id_link, #id_estado').after('<span class="ayuda glyphicon glyphicon-question-sign "> </span>');
        $('.ayuda').hover(function(){
            $(this).next('.help-block').toggle("linear");
        })

		$("#id_pre_pago").change(function() {
			pre = $("#id_precio").val();
			por = $("#id_pre_pago").val();
			$("#id_porcentaje").val(por*100/pre);
		});

		$("#id_sku").ready(function() {
			var str = "{{ultimo}}";
			var letra = str.substring(0,3);
			var nro = parseInt(str.substring(3,6))+1;
			var snro = String(nro);
			var ceros= "";
			for(var i= snro.length;i<3;i++){
				ceros=ceros+0;
			}
			var nro1 = ceros + snro;
			$("#id_sku").val(letra + nro1);
			var campo = document.getElementById('id_sku');
			campo.readOnly=true;
		});
	});
</script>
{% load bootstrap %}
<div class="row">
    <div class="col-lg-8">
        <form action="" method="POST" id="form">
	        {%csrf_token%}
    		{{form|bootstrap_horizontal}}
        <p align="right"><button type= "submit" class="btn btn-success"> Añadir Paquete</button>
        <button type= "reset" class="btn btn-warning"> Limpiar</button> </p>
        </form>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
 $('#form').validate({
  errorElement: "span",
  rules: {
      nombre: {
        minlength: 2,
          required: true
      },
      precio: {
          required: true
      },
      porcentaje: {
          required: true
      },
      pre_pago: {
          required: true
      },
      descripcion: {
          required: true
      }
  },
  highlight: function(element) {
   $(element).closest('.form-group')
   .removeClass('has-success').addClass('has-error');
  },
  success: function(element) {
   element
   .addClass('help-inline')
   .closest('.form-group')
   .removeClass('has-error').addClass('has-success');
  }
 });
});
</script>
{% endblock%}

pyllik/templates/paquete/detail.html
{% extends "layout/base_admin.html" %}
{% block title %}{{obj.nombre}}  <small> <a href="/crm/paquetes"  title="Listar paquetes"><span class="glyphicon glyphicon-list" aria-hidden="true"></span></a></small>{% endblock %}
{% block content %}
<table class="table table-striped">
    <tr>
        <td><b>SKU:</b></td>
        <td>{{obj.sku}}</td>
    </tr>
    <tr>
        <td width="150"><b>Nombre:</b></td>
        <td>{{obj.nombre}}</td>
    </tr>
    <tr>
        <td><b>Precio:</b></td>
        <td>{{obj.precio}}</td>
    </tr>
    <tr>
        <td><b>Pre Pago:</b></td>
        <td>{{obj.pre_pago}}</td>
    </tr>
    <tr>
        <td><b>Porcentaje:</b></td>
        <td>{{obj.porcentaje}}</td>
    </tr>
    <tr>
        <td><b>estado:</b></td>
        <td>{{obj.estado}}</td>
    </tr>
    <tr>
        <td><b>Link:</b></td>
        <td>{{obj.link}}</td>
    </tr>
    <tr>
        <td><b>creado:</b></td>
        <td>{{obj.creado}}</td>
    </tr>
    <tr>
        <td><b>detalle:</b></td>
        <td>{{obj.descripcion|safe }}</td>
    </tr>
</table>
{% endblock%}

pyllik/templates/paquete/edit.html
{% extends "layout/base_admin.html" %}
{% block title %}Editar Paquetes{% endblock %}
{% block options %}
    <li><a href="../detail/{{obj.id}}">Ver</a></li>
    <li class="active"><a href="#">Editar</a></li>
    <li><a href="../add">Nuevo</a></li>
    <li><a href="../../paquetes">Listar</a></li>
{% endblock %}
{% block content %}
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js"></script>
<script type="text/javascript">
	$(function(){
		$("#id_precio, #id_porcentaje").change(function() {
			pre = $("#id_precio").val();
			por = $("#id_porcentaje").val();
			$("#id_pre_pago").val(pre*por/100);
		});

		$("#id_pre_pago").change(function() {
			pre = $("#id_precio").val();
			por = $("#id_pre_pago").val();
			$("#id_porcentaje").val(por*100/pre);
		});

    $('#id_nombre, #id_precio, #id_porcentaje, #id_pre_pago, #id_descripcion, #id_link, #id_estado').after('<span class="ayuda glyphicon glyphicon-question-sign "> </span>');
    $('.ayuda').hover(function(){
        $(this).next('.help-block').toggle("linear");
    })

		$("#id_sku").ready(function() {
		var campo = document.getElementById('id_sku');
			campo.readOnly=true;
		});
	});

</script>
{% load bootstrap %}
<div class="row">
    <div class="col-lg-8">
        <form action="" method="POST" id="form">
            {%csrf_token%}
            {{form|bootstrap_horizontal}}
            <p align="right"><button type= "submit" class="btn btn-success"> Guardar</button>
        <button type= "reset" class="btn btn-warning"> Limpiar</button> </p>
        </form>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
 $('#form').validate({
  errorElement: "span",
  rules: {
      nombre: {
        minlength: 2,
          required: true
      },
      precio: {
          required: true
      },
      porcentaje: {
          required: true
      },
      pre_pago: {
          required: true
      },
      descripcion: {
          required: true
      }
  },
  highlight: function(element) {
   $(element).closest('.form-group')
   .removeClass('has-success').addClass('has-error');
  },
  success: function(element) {
   element
   .addClass('help-inline')
   .closest('.form-group')
   .removeClass('has-error').addClass('has-success');
  }
 });
});
</script>
{% endblock%}

pyllik/templates/paquete/list.html
{% extends "layout/base_admin.html" %}
{% block title %}Paquetes <small> <a href="/crm/paquete/add" title="Agregar paquete"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span></a></small>{% endblock %}
{% block content %}
	<table class="table table-hover table-condensed">
    <thead>
      <tr>
        <th> </th>
        <th>SKU</th>
        <th>Nombre</th>
        <th>Precio (Dolares)</th>
        <th>Adelanto de Reserva (Dolares)</th>
        <th>Descripción</th>
        <th width="80px">Accion</th>
      </tr>
    </thead>
		{% for paquete in objs %}
			<tr>
        <td>
          {% ifequal paquete.estado True %}
          <span style="color:green" title="Habilitado" class="glyphicon glyphicon-ok-sign"></span>
          {% else %} <span style="color:red" title="Desabilitado" class="glyphicon glyphicon-remove-sign"></span>
          {% endifequal %}
        </td>
          <td><a href="paquete/detail/{{paquete.id}}">{{paquete.sku}}</a></td>
    			<td><a href="paquete/detail/{{paquete.id}}">{{paquete.nombre}}</a></td>
          <td>USD <b>{{paquete.precio}}</b></td>
    			<td>USD <b>{{paquete.pre_pago}}</b></td>
    			<td>{{paquete.descripcion|safe }}</td>
          <td align="center">
            <a href="paquete/edit/{{paquete.id}}" title="Editar"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span><a/>  <a href="/reservar/paquete/{{paquete.sku}}" title="Verificar"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span><a/>
              <a href="/crm/reserva/paquete/{{paquete.sku}}" title="Reservar tour"><span  aria-hidden="true" class="glyphicon glyphicon-shopping-cart"></span></a>
          </td>
      		</tr>
		{% endfor %}
	</table>
  <nav>
  <ul class="pagination">
    {% if objs.has_previous %}
    <li>
      <a href="?page={{ objs.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">Anterior</span>
      </a>
    </li>
    {% endif %}
    {% for item in objs.paginator.page_range %}
    {% ifequal item objs.number %}
      <li  class="active"><a href="?page={{ item }}" >{{item }}</a></li>
    {% else %}
      <li ><a href="?page={{ item }}" >{{item }}</a></li>
    {% endifequal %}
    {% endfor %}
    {% if objs.has_next %}
    <li>
      <a href="?page={{ objs.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">Siguiente</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endblock%}